### ISSUE TITLE
Images are not showing.

### ISSUE THREAD

**Issue by rakshit087** [altsam/create_crypto_with_solana_cli#1]
![Screenshot_20211118_005401](https://user-images.githubusercontent.com/50898928/142268703-5a56b963-807a-4dad-9fd8-5248f76df7bf.png)
The images are not showing up. I've tried refresing, but it's not working.

**Comment by altsam** [comment]
Seems to be an indentation issue, will fix it soon.

**Comment by rakshit087** [comment]
I have started working on the fix :)
